from datetime import date

from pydantic import BaseModel, ConfigDict, Field


class BookBase(BaseModel):
    """
    Base schema for Book with common attributes.

    Attributes:
        title (str): The title of the book. Must be between 1 and 200 characters.
        summary (str): A detailed summary or description of the book.
            Must be between 1 and 2000 characters.
        publication_date (date): The date when the book was published.
    """

    title: str = Field(..., min_length=1, max_length=200)
    summary: str = Field(..., min_length=1, max_length=2000)
    publication_date: date = Field(
        ..., le=date.today(), description="Publication date in YYYY-MM-DD format"
    )


class Book(BookBase):
    """
    Schema for retrieving a Book, including database-populated fields.
    Inherits all attributes from BookBase.

    Attributes:
        id (int): Unique identifier for the book, auto-generated by the database.
        author_id (int): ID reference to the book's author.

    Notes:
        This schema is used for responses and includes database-populated fields.
        The model_config enables automatic conversion from SQLAlchemy models.
    """

    model_config = ConfigDict(from_attributes=True)

    id: int
    author_id: int


class AuthorBase(BaseModel):
    """
    Base schema for Author with common attributes.

    Attributes:
        name (str): The full name of the author. Must be between 1 and 100 characters.
        bio (str): Biographical information or description of the author.
            Must be between 1 and 1000 characters.
    """

    name: str = Field(..., min_length=1, max_length=100)
    bio: str = Field(..., min_length=1, max_length=1000)


class Author(AuthorBase):
    """
    Schema for retrieving an Author, including database-populated fields.
    Inherits all attributes from AuthorBase.

    Attributes:
        id (int): Unique identifier for the author, auto-generated by the database.
        books (list[Book] | None): List of books written by the author.
            Defaults to None if books are not included in the query.

    Notes:
        This schema is used for responses and includes database-populated fields.
        The model_config enables automatic conversion from SQLAlchemy models.
    """

    model_config = ConfigDict(from_attributes=True)

    id: int
    books: list[Book] | None = None


class BookListResponse(BaseModel):
    """
    Schema for paginated list of books.

    Attributes:
        books (list[Book]): List of books on the current page.
        prev_page (str | None): URL for the previous page,
            None if current page is first.
        next_page (str | None): URL for the next page, None if current page is last.
        total_pages (int): Total number of pages available.
        total_items (int): Total number of items across all pages.
    """

    model_config = ConfigDict(from_attributes=True)

    books: list[Book]
    prev_page: str | None = None
    next_page: str | None = None
    total_pages: int
    total_items: int
